---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  revisionHistoryLimit: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/zyoma/go-url-shortener:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: "250m"
              memory: "128Mi"
          ports:
            - name: backend
              containerPort: 8080
      imagePullSecrets:
        - name: docker-config-secret

