---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAiellvbWEiLAogICAgICAicGFzc3dvcmQiOiAiZ2hwX29Ga2R0WHZtTFJPWDVocGc0dUNsNlNRNlJTUzgzdTB4dTVOMCIsCiAgICAgICJlbWFpbCI6ICJ6eW9tYUBtYWlsLnJ1IgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: db-dsn
data:
  dns: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnNRbnVSQXBFN1dAcG9zdGdyZXNxbDo1NDMyL3Bvc3RncmVz
type: Opaque
