---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CiAgICAgICAgICAgICJhdXRoIjogIloyaHdYMjlHYTJSMFdIWnRURkpQV0RWb2NHYzBkVU5zTmxOUk5sSlRVemd6ZFRCNGRUVk9NQT09IgogICAgICAgIH0KICAgIH0KfQ==
type: kubernetes.io/dockerconfigjson
