---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJaMmh3WDI5R2EyUjBXSFp0VEZKUFdEVm9jR2MwZFVOc05sTlJObEpUVXpnemRUQjRkVFZPTUE9PSIKICAgICAgICB9CiAgICB9Cn0=
type: kubernetes.io/dockerconfigjson
